//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Commentator")]
[assembly: System.Reflection.AssemblyDescription("Advanced comment behavior for Visual Studio")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCompany("Jared Reisinger")]
[assembly: System.Reflection.AssemblyProduct("Commontator")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2013 Jared Reisinger")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.1 / master / 60c1d877b076754d6252ab17bf429c1bf29e1917")]


