//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Commentator")]
[assembly: System.Reflection.AssemblyDescription("Advanced comment behavior for Visual Studio")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyCompany("Jared Reisinger")]
[assembly: System.Reflection.AssemblyProduct("Commontator")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2013 Jared Reisinger")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.1.0 / master / decdfde9728a5595674d7468683f4ca52b92ef37")]


